package httpserver

import (
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/wrannaman/edge-management/api/configs"

	// docs is generated by Swag CLI, you have to import it.
	"github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
	"github.com/wrannaman/edge-management/api/docs"
	"github.com/wrannaman/edge-management/api/httpserver/device"
	"github.com/wrannaman/edge-management/api/httpserver/user"
)

// Access Control Helper function.
func shouldAccess(wantedGroups []string, groups []interface{}) bool {
	/* Fill depending on your needs */
	return true
}

// @title Edge Management API
// @version 1.0
// @description This will cotroll remote edge devices
// @termsOfService https://sugarkubes.io/terms/

// @contact.name API Support
// @contact.url http://www.xx.io/support
// @contact.email xx@xx.io

// @license.name MIT

// @host localhost:8080
// @BasePath /

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

// StartServer godoc
func StartServer() {
	// gin.SetMode(gin.ReleaseMode)
	r := gin.Default()
	r.Use(gin.Recovery())

	config := &ginSwagger.Config{
		URL: configs.Configs.Self + "/swagger/doc.json", //The url pointing to API definition
	}
	// use ginSwagger middleware to
	r.GET("/swagger/*any", ginSwagger.CustomWrapHandler(config, swaggerFiles.Handler))
	docs.Init()
	// cors
	r.Use(cors.New(cors.Config{
		// AllowOrigins:     []string{"https://foo.com"},
		AllowAllOrigins:  true,
		AllowMethods:     []string{"PUT", "PATCH", "OPTIONS", "GET", "POST"},
		AllowHeaders:     []string{"Origin", "authorization", "Authorization", "Content-Type", "content-type"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
		// AllowOriginFunc: func(origin string) bool {
		// 	return origin == "https://github.com"
		// },
		MaxAge: 12 * time.Hour,
	}))

	// Unauthorized
	r.GET("/ping", PingEndpoint)
	r.GET("/health", PingEndpoint)

	r.Use(user.AttachUser())

	// Users
	r.GET("/v1/user", user.GetUser)

	// Devices
	r.POST("/v1/device", device.CreateDevice)
	r.GET("/v1/devices", device.GetDevices)

	// Authorized
	// authorized := r.Group("/")
	// authorized.Use(gin.BasicAuth(gin.Accounts{
	// 	"admin":  "password",
	// 	"austin": "1234",
	// 	"lena":   "hello2",
	// 	"manu":   "4321",
	// }))
	// {
	// 	authorized.GET("/login", PingEndpoint)
	// 	authorized.GET("/send", SendEndpoint)
	// 	// authorized.POST("/submit", submitEndpoint)
	// 	// authorized.POST("/read", readEndpoint)
	// 	//
	// 	// // nested group
	// 	// testing := authorized.Group("testing")
	// 	// testing.GET("/analytics", analyticsEndpoint)
	// }
	//r.Run() // listen and serve on 0.0.0.0:8080
	r.Run(":8080")
}
